dubbo:
  protocol:
    name: dubbo
    host: 127.0.0.1
    port: -1
  application:
    name: Message
  registry:
    address: nacos://localhost:8848

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: root
    host: 127.0.0.1
    db: message-board
    url: jdbc:p6spy:mysql://${spring.datasource.host}:3307/${spring.datasource.db}?serverTimezone=GMT%2b8
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
