dubbo:
  protocol:
    name: dubbo
    host: 127.0.0.1
    port: -1
  application:
    name: Message
  registry:
    address: nacos://localhost:8848

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    host: 127.0.0.1
    db: message-board
    url: jdbc:mysql://${spring.datasource.host}:3307/${spring.datasource.db}?serverTimezone=GMT%2b8
