version: '3'

services:
  nacos:
    image: nacos/nacos-server:v2.2.2
    container_name: nacos
    environment:
      - MODE=standalone
    ports:
        - "8848:8848"
        - "9848:9848"
    restart: always
